export enum GuildMemberFlag {
  DID_REJOIN = 1 << 0,
  COMPLETED_ONBOARDING = 1 << 1,
  BYPASSES_VERIFICATION = 1 << 2,
  STARTED_ONBOARDING = 1 << 3,
  IS_GUEST = 1 << 4,
  STARTED_HOME_ACTIONS = 1 << 5,
  COMPLETED_HOME_ACTIONS = 1 << 6,
  AUTOMOD_QUARANTINED_USERNAME = 1 << 7,
  DM_SETTINGS_UPSELL_ACKNOWLEDGED = 1 << 9,
  AUTOMOD_QUARANTINED_GUILD_TAG = 1 << 10,
}
