export enum IntegrationType {
    AMAZON_MUSIC = "amazon-music",
    BATTLENET = "battlenet",
    BUNGIE = "bungie",
    BLUESKY = "bluesky",
    CRUNCHYROLL = "crunchyroll",
    DOMAIN = "domain",
    EBAY = "ebay",
    EPICGAMES = "epicgames",
    FACEBOOK = "facebook",
    GITHUB = "github",
    INSTAGRAM = "instagram",
    LEAGUEOFLEGENDS = "leagueoflegends",
    MASTODON = "mastodon",
    PAYPAL = "paypal",
    PLAYSTATION = "playstation",
    REDDIT = "reddit",
    RIOTGAMES = "riotgames",
    ROBLOX = "roblox",
    SPOTIFY = "spotify",
    SKYPE = "skype",
    STEAM = "steam",
    TIKTOK = "tiktok",
    TWITCH = "twitch",
    TWITTER = "twitter",
    XBOX = "xbox",
    YOUTUBE = "youtube"
}