name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize client with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Actually...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Waforix Version
      placeholder: "2.1.0"
    validations:
      required: true

  - type: dropdown
    id: database
    attributes:
      label: Database Type
      options:
        - SQLite
        - PostgreSQL
        - Both
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js/Bun Version
      placeholder: "Node.js 18.17.0 or Bun 1.0.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Ubuntu 22.04, Windows 11, macOS 13"
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages/Logs
      description: Any error messages or relevant logs
      render: shell
      placeholder: Paste error messages here...

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your Waforix configuration (remove sensitive data)
      render: typescript
      placeholder: |
        const client = new StatsClient({
          database: {
            type: 'sqlite',
            path: './stats.db'
          }
        });

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Additional information...
