export enum ChannelFlag {
  GUILD_FEED_REMOVED = 1 << 0,
  PINNED = 1 << 1,
  ACTIVE_CHANNELS_REMOVED = 1 << 2,
  REQUIRE_TAG = 1 << 4,
  IS_SPAM = 1 << 5,
  IS_GUILD_RESOURCE_CHANNEL = 1 << 7,
  CLYDE_AI = 1 << 8,
  IS_SCHEDULED_FOR_DELETION = 1 << 9,
  SUMMARIES_DISABLED = 1 << 11,
  IS_ROLE_SUBSCRIPTION_TEMPLATE_PREVIEW_CHANNEL = 1 << 13,
  IS_BROADCASTING = 1 << 14,
  HIDE_MEDIA_DOWNLOAD_OPTIONS = 1 << 15,
  IS_JOIN_REQUEST_INTERVIEW_CHANNEL = 1 << 16,
  OBFUSCATED = 1 << 17,
  IS_MODERATOR_REPORT_CHANNEL = 1 << 19
}
