name: Format Check

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

permissions:
  contents: read

jobs:
  format-check:
    name: Format Check
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install

      - name: Rebuild Biome binary
        run: bun pm rebuild @biomejs/biome
        
      - name: Check formatting
        run: bun run format
