name: Lint Check
permissions:
  contents: read

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  lint-check:
    name: Lint Check
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npx biome lint src/
