name: Lint Check

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Run linting
        run: bun run lint
