name: Lint Check
permissions:
  contents: read

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  lint-check:
    name: Lint Check
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Rebuild Biome binary
        run: bun pm rebuild @biomejs/biome
        
      - name: Run linting
        run: bun run lint
