name: Publish to NPM
permissions:
  contents: read

on:
  push:
    branches: [main, master]

jobs:
  # Publish to NPM (individual check workflows run separately)
  publish:
    name: Publish to NPM
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Build package
        run: bun run build
        
      - name: Setup Node.js for NPM
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
