name: TypeScript Check
permissions:
  contents: read

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  typescript-check:
    name: TypeScript Check
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma Client
        run: bunx prisma generate

      - name: Run TypeScript check
        run: bunx tsc --noEmit